# -*- coding: utf-8 -*-
"""input functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nh4kU2EtIzmpvDvBLG3xC8dcTSCFkDFE
"""

from PIL import Image
import numpy as np
import torch
import torch.nn.functional as F


def preprocess_image(image, img_size=IMG_SIZE, device=DEVICE):
    """
    Preprocess a single image for the model.

    Accepts either a PIL.Image or a numpy array (as you'd get from
    decoding an uploaded file in a backend endpoint), and returns a
    ready-to-feed tensor of shape [1, 3, img_size, img_size] on `device`.

    Parameters
    ----------
    image : PIL.Image.Image or np.ndarray
        - If numpy: expected HWC, either RGB uint8 or a decoded image
          array (e.g. from cv2.imread — note cv2 gives BGR, so convert
          to RGB *before* calling this function if that's your source).
    img_size : int
        Target square size (matches IMG_SIZE used at training time).
    device : torch.device
        Where to put the resulting tensor.

    Returns
    -------
    torch.Tensor
        Shape [1, 3, img_size, img_size], normalized, on `device`.
    """
    # Normalize input type -> PIL.Image in RGB
    if isinstance(image, np.ndarray):
        if image.dtype != np.uint8:
            # Handle float arrays in [0,1] or [0,255]
            if image.max() <= 1.0:
                image = (image * 255).astype(np.uint8)
            else:
                image = image.astype(np.uint8)
        pil_image = Image.fromarray(image)
    elif isinstance(image, Image.Image):
        pil_image = image
    else:
        raise TypeError(
            f"Unsupported image type: {type(image)}. "
            "Expected PIL.Image.Image or np.ndarray."
        )

    # Ensure 3-channel RGB (handles grayscale, RGBA, palette images, etc.)
    if pil_image.mode != "RGB":
        pil_image = pil_image.convert("RGB")

    # Reuse the same transform pipeline used at eval time
    local_eval_transform = transforms.Compose(
        [
            transforms.Resize((img_size, img_size)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )

    tensor = local_eval_transform(pil_image)  # [3, H, W]
    tensor = tensor.unsqueeze(0)  # add batch dim -> [1, 3, H, W]
    tensor = tensor.to(device)

    return tensor


def predict_image(
    image,
    weights_path,
    backbone=BACKBONE,
    num_classes=3,
    class_to_idx=None,
    device=DEVICE,
    return_probs=True,
):
    """
    Full inference pipeline: preprocess -> load model -> predict.

    Parameters
    ----------
    image : PIL.Image.Image or np.ndarray
        Raw input image (same accepted formats as preprocess_image).
    weights_path : str
        Path to a saved state_dict (.pt/.pth) for SkinLesionModel.
    backbone : str
        Backbone architecture name (must match what the weights were
        trained with). Defaults to the notebook's BACKBONE constant.
    num_classes : int
        Number of output classes.
    class_to_idx : dict, optional
        Mapping like {'benign': 0, 'malignant': 1, ...}. If provided,
        the function also returns the human-readable predicted label.
    device : torch.device
        Device to run inference on.
    return_probs : bool
        If True, also returns the full softmax probability vector.

    Returns
    -------
    dict with keys:
        'pred_idx'   : int, predicted class index
        'pred_label' : str or None, human-readable label if class_to_idx given
        'probs'      : list[float] or None, softmax probabilities per class
        'confidence' : float, probability of the predicted class
    """
    # 1. Preprocess
    input_tensor = preprocess_image(image, device=device)

    # 2. Build model architecture and load trained weights
    model = SkinLesionModel(
        backbone_name=backbone, num_classes=num_classes, pretrained=False
    )
    state_dict = torch.load(weights_path, map_location=device)
    model.load_state_dict(state_dict)
    model = model.to(device)
    model.eval()

    # 3. Inference
    with torch.no_grad():
        logits = model(input_tensor)  # [1, num_classes]
        probs = F.softmax(logits, dim=1)[0]  # [num_classes]
        pred_idx = int(torch.argmax(probs).item())
        confidence = float(probs[pred_idx].item())

    # 4. Map index -> label if mapping provided
    pred_label = None
    if class_to_idx is not None:
        idx_to_class_local = {v: k for k, v in class_to_idx.items()}
        pred_label = idx_to_class_local.get(pred_idx)

    result = {
        "pred_idx": pred_idx,
        "pred_label": pred_label,
        "confidence": confidence,
        "probs": probs.cpu().tolist() if return_probs else None,
    }
    return result
